platform :ios, '16.0'

target 'iosApp' do
  use_frameworks!
  pod 'shared', :path => '../shared'
  pod 'GoogleMaps', '9.2.0'
  pod 'Google-Maps-iOS-Utils', '~> 6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
